spring.application.name=bankdb
server.port=9999
spring.datasource.url=jdbc:mysql://localhost:3306/ormdb
spring.datasource.username=root
spring.datasource.password=ShivaMadhu29@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
